Lang\LanguageBundle\Entity\Herramienta:
    properties:
        freeOrPaid:
            - Choice: { callback: getfreeOrPaidValues, groups: [anadir, actualizar] }  
        nombre:
            - NotBlank: {groups: [anadir, actualizar] }
        web2OrSoft:
            - Choice: { callback: getweb2OrSoftValues, groups: [anadir, actualizar] }  
        getIt:
            - Url: {groups: [anadir, actualizar] } 
        urlAuthor:
            - Url: {groups: [anadir, actualizar] }
        seoUrl:
            - NotBlank: {groups: [anadir, actualizar] }
        foto1:
            - Image: {groups: [anadir] }
            - NotNull: {groups: [anadir] }