<?php

namespace Lang\LanguageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HerramientaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HerramientaRepository extends EntityRepository
{
}
