<?php

namespace Lang\LanguageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OSRepository extends EntityRepository
{
}
